config/routes.rb
DoOrDontButDo::Application.routes.draw do
  root to: 'dodonts#show'

  resources :dodonts, only: [:update, :show, :index, :new, :create]


  resources :signups

  resources :categories, only: [:show]


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dodonts
  validates :name, :instructions, :presence => true
end

app/models/do_dont.rb
class DoDont < ActiveRecord::Base
  validates :content, presence: true
end

app/models/dodont.rb
class Dodont < ActiveRecord::Base
  has_many :votes
  has_many :users, through: :votes

  belongs_to :category
  validates :content, :category_id, presence: true
  validate :screen_for_markup
  before_save :add_markup

  attr_accessible :content, :category_id

  def vote!(cmd)
    if (cmd == "do")
      self.do!
    else
      self.dont!
    end
  end

  def do!
    self.dos += 1
  end

  def dont!
    self.donts += 1   
  end

  private

  def screen_for_markup
    if (self.content =~ /</) || (self.content =~ />/)
      errors.add(:content, "cannot contain scripts or markup")
    end
  end

  def add_markup
    category_name = Category.find(self.category_id).name
    if category_name.downcase == "image"
      self.content = "<img class='image' src='" + self.content + "'>"
    elsif category_name.downcase == "youtube video"
      uri_ending = self.content.split('/')[-1]
      if uri_ending =~ /watch\?v=/
        uri_ending = uri_ending.split('=')[-1]
      end
      self.content = "<iframe class='video' src='//www.youtube.com/embed/" + uri_ending +"' frameborder='0' allowfullscreen></iframe>"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes
  has_many :dodonts, through: :votes
  validates :name, :password, :email, presence: true
  validates :email, uniqueness: true
  validate :email_is_of_valid_format
  validates_confirmation_of :password, :email

  attr_accessible :name, :password, :email, :email_confirmation, :password_confirmation

  def email_is_of_valid_format
    unless self.email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      self.errors[:email] << "is not a valid email"
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    category = Category.find_by_id(params[:id])
    p "----------------------"
    p category
    p "----------------------"
    p category.instructions
    p "----------------------"
    render :json => category.instructions.to_json
  end
end

app/controllers/dodonts_controller.rb
class DodontsController < ApplicationController

  def show
    session[:beenthere] ||= []
    @dodont = Dodont.all.reject{|dd| session[:beenthere].include?(dd.id) }.sample

    # replacing above with this would be cleaner but then the model would need to know about sessions
    # @dodont = Dodont.not_yet_visited

    unless @dodont.nil?
      # session[:beenthere] << @dodont.id
      render :show
    else
      @dodonts = Dodont.all
      render :index
    end
  end

  def update
    @dodont = Dodont.find(params[:id])
    @dodont.vote!(params[:command])
    @dodont.save
    redirect_to root_path
  end

  def index

    @dodonts = Dodont.all
  end

  def new
    @dodont = Dodont.new
  end

  def create
    dodont = Dodont.new
    dodont.content = params[:dodont][:content]
    dodont.category_id = params[:dodont][:category_id]

    if dodont.save
      redirect_to '/'
    else
      @error_messages = dodont.errors.full_messages
      @dodont = Dodont.new
      render :new
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    @user.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dodonts/index.html.erb
<h1 id="title">Top Do-Donts</h1>
<ul id="dodont_list">
<% @dodonts.each do |dodont| %>
  <li class="dodont_element">
    <div class="voting">
      <i class="fa fa-thumbs-o-up"></i><br>
      <i class="fa fa-thumbs-o-down"></i>
    </div>
    <div class="effect">
    <%= dodont.content.html_safe %>
    </div>
  </li>
<% end %>
</ul>

app/views/dodonts/new.html.erb
<h1>Create your own Dodont</h1>

<%= form_for @dodont, url: { action: "create" } do |f| %>
  <p>
    What kind of content would you like to create?
    <%= collection_select(:dodont, :category_id, Category.all, :id, :name) %>
  </p>
  <div id="instructions">Select your content type above, then insert your image/YouTube link or text below:</div>
  <p>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </p>

  <% if @error_messages %>
    <ul class="error_message_list">
    <% @error_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.submit "Post" %>
  </p>
<% end %>

app/views/dodonts/show.html.erb
<h2 id="title">Do -or- Don't (or Do!)</h2>

<ul class="dodont_element">

  <div class="effect">
  
    <%= @dodont.content.html_safe %>
    <div>
    <%= link_to " don't!", dodont_path(@dodont.id, :command => :dont), :method => :put, :class => "fa fa-thumbs-o-down" %>
    <!-- <%= @dodont.donts %> -->
    <br>

    <%= link_to " do!", dodont_path(@dodont.id, :command => :do), :method => :put, :class => "fa fa-thumbs-o-up" %>
    <!-- <%= @dodont.dos %> -->
    </div>
  </div>


</ul>

<%#= link_to "display list", dodonts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoOrDontButDo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <style>
    body {
      /*http://www.colorschemer.com/online.html*/
      text-align: center;
      background: #3380CC;
    }
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//fonts.googleapis.com/css?family=Permanent+Marker:400" rel="stylesheet" type="text/css">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/signups/new.html.erb
<h1>Sign up to start creating Dodonts!</h1>

<%= form_for @user, url: {action: "create"}, html: {class: "signup-form"} do |f| %>
  <%= label_tag(:name, "Name:") %>
  <%= f.text_field :name %><br />
  <%= label_tag(:email, "Email:") %>
  <%= f.email_field :email %><br />
  <%= label_tag(:email_confirmation, "Email confirmed:") %>
  <%= f.email_field :email_confirmation %><br />
  <%= label_tag(:password, "Password:") %>
  <%= f.password_field :password %><br />
  <%= label_tag(:password_confirmation, "Password confirmed:") %>
  <%= f.password_field :password_confirmation %><br />

  <%= f.submit "Sign up" %>
<% end %>